export const types = {
  CART_ADD_ITEM: "CART_ADD_ITEM",
  CART_REMOVE_ITEM: "CART_REMOVE_ITEM",
  CART_UPDATE_ITEM: "CART_UPDATE_ITEM",
  CART_CLEAR: "CART_CLEAR",

  PRODUCTS_WRITE: "PRODUCTS_WRITE",
  PRODUCTS_CLEAR: "PRODUCTS_CLEAR",
};
